# Generated by Django 5.1.6 on 2025-03-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TradeMember",
        ),
    ]
